### ISSUE TITLE
M2Crypto.SSL.Checker does not support IP addresses in subjectAltName

### ISSUE THREAD

**Issue by mtrmac** [martinpaljak/M2Crypto#19]
https://bugzilla.redhat.com/show_bug.cgi?id=1080142 .  I plan to submit a patch eventually, filing this now just to make it visible.

**Comment by mcepl** [comment]
New version 0.22.4 has been released on PyPI and the new upstream for this project is now officially https://gitlab.com/m2crypto/m2crypto/ Please, file all issues, merge requests, etc. there.

This ticket can be closed now.

**Comment by mtrmac** [comment]
Fix confirmed in 0.22.5.
