### ISSUE TITLE
Can't reliably create an X509 cert

### ISSUE THREAD

**Issue by hufman** [martinpaljak/M2Crypto#41]
I found some [example code](https://gist.github.com/eskil/2338529) and made a simple helper function to easily generate certs. However, I found that it was randomly segfaults. I posted a test case on https://github.com/hufman/m2crypto_crash with a Travis build setup showing the crash.
Am I doing something wrong in my cert building?

**Comment by mcepl** [comment]
Would patch from #42 help? If not, I am trying to revive the upstream of the project at https://gitlab.com/m2crypto/m2crypto/ so you can file a issue there.

**Comment by hufman** [comment]
I tested the latest master code, which included that patch, and it didn't change the result.
Closing the issue because it's been migrated to the new upstream bug tracker.
