### ISSUE TITLE
test_x509_name fails with OpenSSL 1.0.1h

### ISSUE THREAD

**Issue by mtrmac** [martinpaljak/M2Crypto#42]
The added comment says it all; also modified the assertion to make the different hash value visible.

**Comment by mcepl** [comment]
Should be included in the new upstream. See https://github.com/mcepl/M2Crypto/issues/5#issuecomment-142592062 for more information.

**Comment by mcepl** [comment]
New version 0.22.4 has been released on PyPI and the new upstream for this project is now officially https://gitlab.com/m2crypto/m2crypto/ Please, file all issues, merge requests, etc. there.

This ticket can be closed now.

**Comment by mtrmac** [comment]
Fix confirmed in 0.22.5.
