### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by idgserpro** [martinpaljak/M2Crypto#52]
I'm using version 0.22.3 in RHEL distros and having some problems. I saw that https://github.com/martinpaljak/M2Crypto/commit/9abed178ed257d1bd2efbb16f7512e964f85d006 gives a better identification to these platforms.

Do you have any plans for a 0.22.4 or 0.23.0 release on pypi on a foreseeable future so we could use this fix? Thanks!

**Comment by idgserpro** [comment]
Any news about this subject?

You say in ```README.md``` that

> The official repository shall soon live at https://github.com/M2Crypto/M2Crypto.

How is the planning to merge those two? Will the release be made from there? Should I post an issue like this one on https://github.com/M2Crypto/M2Crypto instead? Thanks!

**Comment by mcepl** [comment]
See https://github.com/mcepl/M2Crypto/issues/5#issuecomment-142592062 for the latest news.

**Comment by mcepl** [comment]
New version 0.22.4 has been released on PyPI and the new upstream for this project is now officially https://gitlab.com/m2crypto/m2crypto/ Please, file all issues, merge requests, etc. there.

This ticket can be closed now.

**Comment by idgserpro** [comment]
Thank you @mcepl!
