### ISSUE TITLE
NameError: global name 'm' is not defined

### ISSUE THREAD

**Issue by spaceone** [martinpaljak/M2Crypto#67]
pyflakes /usr/lib/python2.7/dist-packages/M2Crypto/ASN1.py
/usr/lib/python2.7/dist-packages/M2Crypto/ASN1.py:177: undefined name 'm'

  File "/usr/lib/python2.7/dist-packages/M2Crypto/ASN1.py", line 177, in get_datetime
    raise ValueError("Invalid date %s: Invalid month: %s" % (date, m))
NameError: global name 'm' is not defined

Fix is s/m/month/

**Comment by allardhoeve** [comment]
https://github.com/martinpaljak/M2Crypto/blob/9abed178ed257d1bd2efbb16f7512e964f85d006/M2Crypto/ASN1.py#L177

**Comment by spaceone** [comment]
Yes? Here, you can merge it directly via my pull request: https://github.com/martinpaljak/M2Crypto/pull/84

**Comment by mcepl** [comment]
New version 0.22.4 has been released on PyPI and the new upstream for this project is now officially https://gitlab.com/m2crypto/m2crypto/ Please, file all issues, merge requests, etc. there.

This ticket can be closed now.

**Comment by spaceone** [comment]
https://gitlab.com/m2crypto/m2crypto/commit/62191971f697c0e26e6e948a3a6d70f75a69ad5e
