### ISSUE TITLE
Spurious failures in test_cookie_str_changed_mac

### ISSUE THREAD

**Issue by mtrmac** [martinpaljak/M2Crypto#70]
The test tests that a modification of MAC is detected by replacing one character by 'X', but from time to time the original MAC may have an 'X' in that place, in which case the modification doesn’t happen.

The patch ensures that the cookie is really modified; the other two tests are structurally similar and have the same fundamental problem in principle, but it is unlikely (or impossible?) for them to have the same value; still, the patch modifies the others as well for reliability and consistency.

**Comment by mcepl** [comment]
Fixed upstream https://gitlab.com/m2crypto/m2crypto/issues/53

This ticket can be closed now.

**Comment by mtrmac** [comment]
Fix confirmed in 0.22.5.
