### ISSUE TITLE
-----BEGIN TRUSTED CERTIFICATE------ doesn't work 

### ISSUE THREAD

**Issue by SunTzuTech** [martinpaljak/M2Crypto#86]
working with M2Crypto-0.22.6.rc3, I've noticed a strange behavior I didn't expect.

My original self signed certificate has the header and trailer:

-----BEGIN TRUSTED CERTIFICATE-----

-----END TRUSTED CERTIFICATE-----

when I run my script, I get the following output.

When I swap in the same cert, having removed " TRUSTED", so it reads 

-----BEGIN CERTIFICATE-----

-----END CERTIFICATE------

the script works as expected.   Is the parser that fragile?

Traceback (most recent call last):
  File "./emailsign_filter.py", line 240, in <module>
    x509 = X509.load_cert(to_cert)
  File "/usr/lib64/python2.6/site-packages/M2Crypto-0.22.6.rc3-py2.6-linux-x86_64.egg/M2Crypto/X509.py", line 611, in load_cert
    return load_cert_bio(bio)
  File "/usr/lib64/python2.6/site-packages/M2Crypto-0.22.6.rc3-py2.6-linux-x86_64.egg/M2Crypto/X509.py", line 639, in load_cert_bio
    raise X509Error(Err.get_error())
X509Error: 140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:2007507E:BIO routines:MEM_WRITE:write to read only BIO:bss_mem.c:183:
140267904026368:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:

**Comment by mcepl** [comment]
@SunTzuTech , please, file an issue at https://gitlab.com/m2crypto/m2crypto/issues and attach an example script demonstrating the problem. Thank you.

**Comment by SunTzuTech** [comment]
KK. I've put together an example with certs and will post it on the new site
